"""Minimal single-GPU GRPO training with vLLM CUDA IPC updates."""

from __future__ import annotations

import asyncio
import os
from dataclasses import dataclass
from typing import Any

# Start the local Ray cluster with only one physical GPU visible. Inside each
# Ray actor that GPU is exposed as cuda:0.
os.environ.setdefault("CUDA_VISIBLE_DEVICES", "0")

import ray
import torch
from ray.util.placement_group import placement_group, remove_placement_group
from ray.util.scheduling_strategies import PlacementGroupSchedulingStrategy
from transformers import AutoModelForCausalLM, AutoTokenizer
from vllm import LLM, SamplingParams
from vllm.config import WeightTransferConfig
from vllm.distributed.weight_transfer.ipc_engine import (
    IPCTrainerSendWeightsArgs,
    IPCWeightTransferEngine,
)

from chito import (
    InferenceRequest,
    InferenceResult,
    RolloutConfig,
    RolloutEngine,
    RolloutPrompt,
    RolloutSample,
    SingleTurnWorkflow,
    TrainingBatch,
)


MODEL = os.environ.get("CHITO_MODEL", "Qwen/Qwen2.5-0.5B-Instruct")
DEVICE = "cuda:0"
DTYPE = torch.float16
GROUP_SIZE = 4
MAX_NEW_TOKENS = 24
LEARNING_RATE = 1e-5
CLIP_EPSILON = 0.2
PACKED_BUFFER_BYTES = 320 * 1024 * 1024
TOY_TASKS = (
    ("Name the color of a clear daytime sky in one short sentence.", "blue"),
    ("Write two plus two in words in one short sentence.", "four"),
    ("Name the opposite of cold in one short sentence.", "warm"),
)


class ColocatedLlm(LLM):
    """Configure vLLM's Ray worker to share one GPU with the trainer."""

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        os.environ.pop("CUDA_VISIBLE_DEVICES", None)
        os.environ["VLLM_RAY_PER_WORKER_GPUS"] = "0.4"
        os.environ["VLLM_RAY_BUNDLE_INDICES"] = "0"
        os.environ["VLLM_ALLOW_INSECURE_SERIALIZATION"] = "1"
        super().__init__(*args, **kwargs)


def clipped_grpo_loss(
    model: torch.nn.Module,
    batch: TrainingBatch,
) -> torch.Tensor:
    sample_losses: list[torch.Tensor] = []

    for group in batch.groups:
        rewards = torch.tensor(
            [sample.reward for sample in group.samples],
            dtype=torch.float32,
            device=DEVICE,
        )
        advantages = (rewards - rewards.mean()) / (
            rewards.std(unbiased=False) + 1e-6
        )

        for sample, advantage in zip(group.samples, advantages, strict=True):
            token_ids = torch.tensor(sample.token_ids, device=DEVICE)
            logits = model(token_ids[:-1].unsqueeze(0)).logits[0]

            # Logit t predicts token t+1. The shifted mask keeps only tokens
            # generated by the policy in the GRPO objective.
            next_tokens = token_ids[1:]
            current_logprobs = torch.log_softmax(logits.float(), dim=-1)
            current_logprobs = current_logprobs.gather(
                -1, next_tokens.unsqueeze(-1)
            ).squeeze(-1)
            behavior_logprobs = torch.tensor(
                sample.logprobs[1:], dtype=torch.float32, device=DEVICE
            )
            generated_mask = torch.tensor(
                sample.loss_mask[1:], dtype=torch.bool, device=DEVICE
            )

            ratio = torch.exp(current_logprobs - behavior_logprobs)
            unclipped = ratio * advantage
            clipped = ratio.clamp(
                1.0 - CLIP_EPSILON, 1.0 + CLIP_EPSILON
            ) * advantage
            sample_losses.append(
                -torch.minimum(unclipped, clipped)[generated_mask].mean()
            )

    return torch.stack(sample_losses).mean()


@ray.remote
class Trainer:
    """Keep training weights on the colocated GPU and publish them via IPC."""

    def __init__(self, model_name: str, llm_handle: Any) -> None:
        self.model = AutoModelForCausalLM.from_pretrained(
            model_name,
            dtype=DTYPE,
        ).to(DEVICE)
        self.model.config.use_cache = False
        self.model.train()
        self.optimizer = torch.optim.SGD(
            self.model.parameters(), lr=LEARNING_RATE
        )
        self.llm_handle = llm_handle

    def init_weight_transfer(self) -> None:
        ray.get(
            self.llm_handle.init_weight_transfer_engine.remote(
                dict(init_info={})
            )
        )

    def train_step(self, batch: TrainingBatch) -> float:
        self.optimizer.zero_grad(set_to_none=True)
        loss = clipped_grpo_loss(self.model, batch)
        loss.backward()
        self.optimizer.step()
        torch.cuda.synchronize()
        return float(loss.item())

    def broadcast_weights(self) -> None:
        send_args = IPCTrainerSendWeightsArgs(
            send_mode="ray",
            llm_handle=self.llm_handle,
            packed=True,
            packed_buffer_size_bytes=PACKED_BUFFER_BYTES,
        )
        IPCWeightTransferEngine.trainer_send_weights(
            iterator=self.model.named_parameters(),
            trainer_args=send_args,
        )


@dataclass(frozen=True, slots=True)
class IpcWeightUpdate:
    """The trainer actor now holds the complete weights to publish."""

    trainer: Any


async def remote_result(object_ref: Any) -> Any:
    return await asyncio.to_thread(ray.get, object_ref)


class RayIpcVllmBackend:
    """Small sample adapter from a Ray-hosted LLM to chito's backend API."""

    def __init__(self, llm_handle: Any) -> None:
        self.llm_handle = llm_handle
        self.sampling_params = SamplingParams(
            n=1,
            max_tokens=MAX_NEW_TOKENS,
            temperature=1.0,
            top_p=1.0,
            logprobs=0,
            detokenize=False,
        )
        self.closed = False

    async def generate(self, request: InferenceRequest) -> InferenceResult:
        prompt = {"prompt_token_ids": list(request.prompt.token_ids)}
        outputs = await remote_result(
            self.llm_handle.generate.remote(
                prompt,
                self.sampling_params,
                use_tqdm=False,
            )
        )
        output = outputs[0]
        completion = output.outputs[0]
        token_ids = tuple(int(token_id) for token_id in completion.token_ids)
        if completion.logprobs is None:
            raise RuntimeError("vLLM did not return sampled-token logprobs")
        logprobs = tuple(
            float(candidates[token_id].logprob)
            for token_id, candidates in zip(
                token_ids, completion.logprobs, strict=True
            )
        )
        return InferenceResult(
            output_token_ids=token_ids,
            output_logprobs=logprobs,
            policy_version=request.policy_version,
        )

    async def update_weights(
        self,
        update: object,
        *,
        new_policy_version: int,
    ) -> None:
        if not isinstance(update, IpcWeightUpdate):
            raise TypeError("CUDA IPC requires an IpcWeightUpdate")

        await remote_result(
            self.llm_handle.sleep.remote(level=0, mode="wait")
        )
        await remote_result(
            self.llm_handle.start_weight_update.remote(
                is_checkpoint_format=True
            )
        )
        await remote_result(update.trainer.broadcast_weights.remote())
        await remote_result(self.llm_handle.finish_weight_update.remote())
        await remote_result(
            self.llm_handle.wake_up.remote(tags=["scheduling"])
        )

    async def aclose(self) -> None:
        if self.closed:
            return
        self.closed = True
        await asyncio.to_thread(ray.kill, self.llm_handle)


async def main() -> None:
    tokenizer = AutoTokenizer.from_pretrained(MODEL)
    prompts: list[RolloutPrompt] = []
    for index, (question, target) in enumerate(TOY_TASKS):
        rendered = tokenizer.apply_chat_template(
            [{"role": "user", "content": question}],
            tokenize=False,
            add_generation_prompt=True,
        )
        token_ids = tokenizer.encode(rendered, add_special_tokens=False)
        prompts.append(
            RolloutPrompt(
                prompt_id=f"toy-{index}",
                token_ids=tuple(token_ids),
                metadata={"target": target},
            )
        )

    release_next_prompt = [asyncio.Event() for _ in prompts[:-1]]

    async def prompt_source():
        for index, prompt in enumerate(prompts):
            if index > 0:
                await release_next_prompt[index - 1].wait()
            yield prompt

    async def reward(prompt: RolloutPrompt, sample: RolloutSample) -> float:
        output_ids = sample.token_ids[len(prompt.token_ids) :]
        answer = tokenizer.decode(output_ids, skip_special_tokens=True).lower()
        target = str(prompt.metadata["target"]).lower()
        return float(target in answer) - 0.01 * len(output_ids)

    ray.init()
    gpu_group = placement_group([{"GPU": 1, "CPU": 0}])
    await remote_result(gpu_group.ready())
    colocated = PlacementGroupSchedulingStrategy(
        placement_group=gpu_group,
        placement_group_capture_child_tasks=True,
    )

    llm = ray.remote(
        num_cpus=0,
        num_gpus=0,
        scheduling_strategy=colocated,
    )(ColocatedLlm).remote(
        model=MODEL,
        dtype="float16",
        enforce_eager=True,
        tensor_parallel_size=1,
        distributed_executor_backend="ray",
        gpu_memory_utilization=0.4,
        max_model_len=512,
        max_num_seqs=GROUP_SIZE,
        disable_log_stats=True,
        weight_transfer_config=WeightTransferConfig(backend="ipc"),
        load_format="dummy",
    )
    trainer = Trainer.options(
        num_cpus=0,
        num_gpus=0.1,
        scheduling_strategy=colocated,
    ).remote(MODEL, llm)

    backend = RayIpcVllmBackend(llm)
    engine = RolloutEngine(
        backend=backend,
        workflow=SingleTurnWorkflow(),
        reward_function=reward,
        config=RolloutConfig(
            group_size=GROUP_SIZE,
            train_batch_size=1,
            max_concurrent_groups=1,
        ),
    )
    weights = IpcWeightUpdate(trainer)

    try:
        await remote_result(trainer.init_weight_transfer.remote())
        # vLLM started with dummy weights; install the trainer checkpoint before
        # admitting the first rollout while keeping policy_version at zero.
        await backend.update_weights(weights, new_policy_version=0)

        await engine.rollout(prompt_source())
        for step in range(1, len(prompts) + 1):
            batch = await engine.next_batch()
            loss = await remote_result(trainer.train_step.remote(batch))
            policy_version = await engine.update_weights(weights)
            print(
                f"step={step} loss={loss:.4f} "
                f"policy_version={policy_version}"
            )

            if step < len(prompts):
                release_next_prompt[step - 1].set()
    finally:
        try:
            await engine.aclose()
        finally:
            ray.kill(trainer)
            remove_placement_group(gpu_group)
            ray.shutdown()


if __name__ == "__main__":
    asyncio.run(main())
